// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Nexorsys.Identity.Infrastructure;

#nullable disable

namespace Nexorsys.Identity.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260915065827_WorkstationLifecycle")]
    partial class WorkstationLifecycle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Nexorsys.Identity.Core.AnsDelegationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AdminUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("admin_user_id");

                    b.Property<bool>("IsDeclaredToGovernment")
                        .HasColumnType("boolean")
                        .HasColumnName("is_declared_to_government");

                    b.Property<string>("NfcBadgeUid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nfc_badge_uid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateTime>("PairedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("paired_at");

                    b.Property<string>("RppsNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rpps_number");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("VerificationMethod")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("verification_method");

                    b.HasKey("Id")
                        .HasName("pk_ans_delegation_logs");

                    b.HasIndex("AdminUserId")
                        .HasDatabaseName("ix_ans_delegation_logs_admin_user_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_ans_delegation_logs_user_id");

                    b.ToTable("ans_delegation_logs", (string)null);
                });

            modelBuilder.Entity("Nexorsys.Identity.Core.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("client_id");

                    b.Property<string>("ClientSecret")
                        .HasColumnType("text")
                        .HasColumnName("client_secret");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string[]>("RedirectUris")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("redirect_uris");

                    b.HasKey("Id")
                        .HasName("pk_applications");

                    b.HasIndex("ClientId")
                        .IsUnique()
                        .HasDatabaseName("ix_applications_client_id");

                    b.ToTable("applications", (string)null);
                });

            modelBuilder.Entity("Nexorsys.Identity.Core.ApplicationSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApplicationName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("application_name");

                    b.Property<string>("Department")
                        .HasColumnType("text")
                        .HasColumnName("department");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp")
                        .HasColumnName("end_time");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp")
                        .HasColumnName("start_time");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid?>("WorkstationId")
                        .HasColumnType("uuid")
                        .HasColumnName("workstation_id");

                    b.HasKey("Id")
                        .HasName("pk_application_sessions");

                    b.HasIndex("WorkstationId")
                        .HasDatabaseName("ix_application_sessions_workstation_id");

                    b.HasIndex("UserId", "ApplicationName")
                        .HasDatabaseName("ix_application_sessions_user_id_application_name");

                    b.ToTable("application_sessions", (string)null);
                });

            modelBuilder.Entity("Nexorsys.Identity.Core.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<string>("NewValues")
                        .HasColumnType("text")
                        .HasColumnName("new_values");

                    b.Property<string>("OldValues")
                        .HasColumnType("text")
                        .HasColumnName("old_values");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid?>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_id");

                    b.Property<string>("ResourceType")
                        .HasColumnType("text")
                        .HasColumnName("resource_type");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_audit_logs_user_id");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("Nexorsys.Identity.Core.AuthenticationEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Department")
                        .HasColumnType("text")
                        .HasColumnName("department");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider_type");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("result");

                    b.Property<string>("RiskLevel")
                        .HasColumnType("text")
                        .HasColumnName("risk_level");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp")
                        .HasColumnName("timestamp");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid?>("WorkstationId")
                        .HasColumnType("uuid")
                        .HasColumnName("workstation_id");

                    b.HasKey("Id")
                        .HasName("pk_authentication_events");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_authentication_events_user_id");

                    b.HasIndex("WorkstationId")
                        .HasDatabaseName("ix_authentication_events_workstation_id");

                    b.HasIndex("Timestamp", "UserId", "WorkstationId")
                        .HasDatabaseName("ix_authentication_events_timestamp_user_id_workstation_id");

                    b.ToTable("authentication_events", (string)null);
                });

            modelBuilder.Entity("Nexorsys.Identity.Core.AuthenticationPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssuranceLevel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("assurance_level");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("PolicyName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("policy_name");

                    b.Property<Guid?>("ProviderId")
                        .HasColumnType("uuid")
                        .HasColumnName("provider_id");

                    b.Property<string>("TargetApplication")
                        .HasColumnType("text")
                        .HasColumnName("target_application");

                    b.Property<string>("TargetGroup")
                        .HasColumnType("text")
                        .HasColumnName("target_group");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_authentication_policies");

                    b.HasIndex("ProviderId")
                        .HasDatabaseName("ix_authentication_policies_provider_id");

                    b.ToTable("authentication_policies", (string)null);
                });

            modelBuilder.Entity("Nexorsys.Identity.Core.CredentialProviderFleet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("EnrollmentCount")
                        .HasColumnType("integer")
                        .HasColumnName("enrollment_count");

                    b.Property<string>("InstalledVersion")
                        .HasColumnType("text")
                        .HasColumnName("installed_version");

                    b.Property<DateTime?>("LastCheckInAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("last_check_in_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("ProviderStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider_status");

                    b.Property<string>("WindowsVersion")
                        .HasColumnType("text")
                        .HasColumnName("windows_version");

                    b.Property<Guid>("WorkstationId")
                        .HasColumnType("uuid")
                        .HasColumnName("workstation_id");

                    b.HasKey("Id")
                        .HasName("pk_credential_provider_fleets");

                    b.HasIndex("WorkstationId")
                        .IsUnique()
                        .HasDatabaseName("ix_credential_provider_fleets_workstation_id");

                    b.ToTable("credential_provider_fleets", (string)null);
                });

            modelBuilder.Entity("Nexorsys.Identity.Core.DepartmentPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<TimeSpan>("AllowedAccessEnd")
                        .HasColumnType("interval")
                        .HasColumnName("allowed_access_end");

                    b.Property<TimeSpan>("AllowedAccessStart")
                        .HasColumnType("interval")
                        .HasColumnName("allowed_access_start");

                    b.Property<string>("AllowedAuthenticationMethods")
                        .HasColumnType("text")
                        .HasColumnName("allowed_authentication_methods");

                    b.Property<string>("AuthorizedWorkstations")
                        .HasColumnType("text")
                        .HasColumnName("authorized_workstations");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("department");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("RequiredAssuranceLevel")
                        .HasColumnType("text")
                        .HasColumnName("required_assurance_level");

                    b.Property<string>("RequiredRiskLevel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("required_risk_level");

                    b.Property<int>("SessionTimeoutMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("session_timeout_minutes");

                    b.HasKey("Id")
                        .HasName("pk_department_policies");

                    b.ToTable("department_policies", (string)null);
                });

            modelBuilder.Entity("Nexorsys.Identity.Core.FeatureFlag", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid?>("EnabledByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("enabled_by_user_id");

                    b.Property<DateTime?>("EnabledFrom")
                        .HasColumnType("timestamp")
                        .HasColumnName("enabled_from");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_feature_flags");

                    b.ToTable("feature_flags", (string)null);
                });

            modelBuilder.Entity("Nexorsys.Identity.Core.FederationToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssuranceLevel")
                        .HasColumnType("text")
                        .HasColumnName("assurance_level");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("expires_at");

                    b.Property<string>("ExternalSubjectId")
                        .HasColumnType("text")
                        .HasColumnName("external_subject_id");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_revoked");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("issued_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider_type");

                    b.Property<string>("TokenReference")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_reference");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_federation_tokens");

                    b.HasIndex("UserId", "ProviderType")
                        .HasDatabaseName("ix_federation_tokens_user_id_provider_type");

                    b.ToTable("federation_tokens", (string)null);
                });

            modelBuilder.Entity("Nexorsys.Identity.Core.GroupRoleMembership", b =>
                {
                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.HasKey("GroupId", "RoleId")
                        .HasName("pk_group_role_memberships");

                    b.ToTable("group_role_memberships", (string)null);
                });

            modelBuilder.Entity("Nexorsys.Identity.Core.IdentityProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConfigurationJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("configuration_json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at");

                    b.Property<string>("HealthStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("health_status");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<DateTime?>("LastHealthCheck")
                        .HasColumnType("timestamp")
                        .HasColumnName("last_health_check");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider_name");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider_type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_identity_providers");

                    b.HasIndex("ProviderType")
                        .IsUnique()
                        .HasDatabaseName("ix_identity_providers_provider_type");

                    b.ToTable("identity_providers", (string)null);
                });

            modelBuilder.Entity("Nexorsys.Identity.Core.KioskSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BadgeUid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("badge_uid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("expires_at");

                    b.Property<string>("NfcUid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nfc_uid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("SessionToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("session_token");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid?>("WorkstationId")
                        .HasColumnType("uuid")
                        .HasColumnName("workstation_id");

                    b.HasKey("Id")
                        .HasName("pk_kiosk_sessions");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_kiosk_sessions_user_id");

                    b.ToTable("kiosk_sessions", (string)null);
                });

            modelBuilder.Entity("Nexorsys.Identity.Core.MigrationPhase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ActivatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("activated_at");

                    b.Property<string>("ActiveProvidersJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("active_providers_json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("FederationEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("federation_enabled");

                    b.Property<bool>("IsCurrentPhase")
                        .HasColumnType("boolean")
                        .HasColumnName("is_current_phase");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("PhaseName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phase_name");

                    b.HasKey("Id")
                        .HasName("pk_migration_phases");

                    b.HasIndex("IsCurrentPhase")
                        .HasDatabaseName("ix_migration_phases_is_current_phase");

                    b.ToTable("migration_phases", (string)null);
                });

            modelBuilder.Entity("Nexorsys.Identity.Core.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_organizations");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_organizations_slug");

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("Nexorsys.Identity.Core.OrganizationLicense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("expiry_date");

                    b.Property<string>("LicensedModules")
                        .HasColumnType("text")
                        .HasColumnName("licensed_modules");

                    b.Property<int>("LicensedUsers")
                        .HasColumnType("integer")
                        .HasColumnName("licensed_users");

                    b.Property<int>("LicensedWorkstations")
                        .HasColumnType("integer")
                        .HasColumnName("licensed_workstations");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("SupportLevel")
                        .HasColumnType("text")
                        .HasColumnName("support_level");

                    b.HasKey("Id")
                        .HasName("pk_organization_licenses");

                    b.ToTable("organization_licenses", (string)null);
                });

            modelBuilder.Entity("Nexorsys.Identity.Core.PermissionDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.HasKey("Id")
                        .HasName("pk_permission_definitions");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_permission_definitions_key");

                    b.ToTable("permission_definitions", (string)null);
                });

            modelBuilder.Entity("Nexorsys.Identity.Core.PinResetRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("approved_at");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by");

                    b.Property<string>("BadgeUid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("badge_uid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("requested_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid?>("WorkstationId")
                        .HasColumnType("uuid")
                        .HasColumnName("workstation_id");

                    b.HasKey("Id")
                        .HasName("pk_pin_reset_requests");

                    b.HasIndex("ApprovedBy")
                        .HasDatabaseName("ix_pin_reset_requests_approved_by");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_pin_reset_requests_user_id");

                    b.HasIndex("WorkstationId")
                        .HasDatabaseName("ix_pin_reset_requests_workstation_id");

                    b.ToTable("pin_reset_requests", (string)null);
                });

            modelBuilder.Entity("Nexorsys.Identity.Core.RoleDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsSystemRole")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system_role");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.HasKey("Id")
                        .HasName("pk_role_definitions");

                    b.HasIndex("OrganizationId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_role_definitions_organization_id_name");

                    b.ToTable("role_definitions", (string)null);
                });

            modelBuilder.Entity("Nexorsys.Identity.Core.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.HasKey("RoleId", "PermissionId")
                        .HasName("pk_role_permissions");

                    b.ToTable("role_permissions", (string)null);
                });

            modelBuilder.Entity("Nexorsys.Identity.Core.SecurityGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.HasKey("Id")
                        .HasName("pk_security_groups");

                    b.HasIndex("OrganizationId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_security_groups_organization_id_name");

                    b.ToTable("security_groups", (string)null);
                });

            modelBuilder.Entity("Nexorsys.Identity.Core.SessionEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at");

                    b.Property<string>("EventDescription")
                        .HasColumnType("text")
                        .HasColumnName("event_description");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.HasKey("Id")
                        .HasName("pk_session_events");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_session_events_session_id");

                    b.ToTable("session_events", (string)null);
                });

            modelBuilder.Entity("Nexorsys.Identity.Core.Site", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.HasKey("Id")
                        .HasName("pk_sites");

                    b.HasIndex("OrganizationId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_sites_organization_id_name");

                    b.ToTable("sites", (string)null);
                });

            modelBuilder.Entity("Nexorsys.Identity.Core.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AdGuid")
                        .HasColumnType("text")
                        .HasColumnName("ad_guid");

                    b.Property<string>("BadgeType")
                        .HasColumnType("text")
                        .HasColumnName("badge_type");

                    b.Property<string>("BadgeUid")
                        .HasColumnType("text")
                        .HasColumnName("badge_uid");

                    b.Property<string>("CpsId")
                        .HasColumnType("text")
                        .HasColumnName("cps_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at");

                    b.Property<bool>("CredentialProviderEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("credential_provider_enabled");

                    b.Property<string>("Department")
                        .HasColumnType("text")
                        .HasColumnName("department");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("DistinguishedName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("distinguished_name");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("EmployeeId")
                        .HasColumnType("text")
                        .HasColumnName("employee_id");

                    b.Property<DateTime?>("EnrollmentExpirationDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("enrollment_expiration_date");

                    b.Property<string>("EnrollmentStatus")
                        .HasColumnType("text")
                        .HasColumnName("enrollment_status");

                    b.Property<string>("EnrollmentWorkstation")
                        .HasColumnType("text")
                        .HasColumnName("enrollment_workstation");

                    b.Property<int>("FailedPinAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("failed_pin_attempts");

                    b.Property<string>("FidoId")
                        .HasColumnType("text")
                        .HasColumnName("fido_id");

                    b.Property<string>("FirstName")
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsLocalProfile")
                        .HasColumnType("boolean")
                        .HasColumnName("is_local_profile");

                    b.Property<DateTime?>("LastCredentialRefresh")
                        .HasColumnType("timestamp")
                        .HasColumnName("last_credential_refresh");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("last_login_at");

                    b.Property<string>("LastName")
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<DateTime?>("LastWindowsLogin")
                        .HasColumnType("timestamp")
                        .HasColumnName("last_windows_login");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("timestamp")
                        .HasColumnName("locked_until");

                    b.Property<string>("ManagerAdGuid")
                        .HasColumnType("text")
                        .HasColumnName("manager_ad_guid");

                    b.Property<bool>("MustChangePin")
                        .HasColumnType("boolean")
                        .HasColumnName("must_change_pin");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("RequiresReEnrollment")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_re_enrollment");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("RppsNumber")
                        .HasColumnType("text")
                        .HasColumnName("rpps_number");

                    b.Property<string>("SamAccountName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sam_account_name");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at");

                    b.Property<bool>("WindowsAuthEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("windows_auth_enabled");

                    b.Property<string>("WindowsAuthMode")
                        .HasColumnType("text")
                        .HasColumnName("windows_auth_mode");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("AdGuid")
                        .IsUnique()
                        .HasDatabaseName("ix_users_ad_guid");

                    b.HasIndex("BadgeUid")
                        .HasDatabaseName("ix_users_badge_uid");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Nexorsys.Identity.Core.UserDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssuranceLevel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("assurance_level");

                    b.Property<string>("CertificationReference")
                        .HasColumnType("text")
                        .HasColumnName("certification_reference");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceIdentifier")
                        .HasColumnType("text")
                        .HasColumnName("device_identifier");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("device_name");

                    b.Property<string>("DeviceSerial")
                        .HasColumnType("text")
                        .HasColumnName("device_serial");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("device_type");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsCertified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_certified");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("last_used_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid?>("RegisteredBy")
                        .HasColumnType("uuid")
                        .HasColumnName("registered_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_devices");

                    b.HasIndex("DeviceIdentifier")
                        .HasDatabaseName("ix_user_devices_device_identifier");

                    b.HasIndex("RegisteredBy")
                        .HasDatabaseName("ix_user_devices_registered_by");

                    b.HasIndex("UserId", "DeviceType")
                        .HasDatabaseName("ix_user_devices_user_id_device_type");

                    b.ToTable("user_devices", (string)null);
                });

            modelBuilder.Entity("Nexorsys.Identity.Core.UserGroupMembership", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.HasKey("UserId", "GroupId")
                        .HasName("pk_user_group_memberships");

                    b.ToTable("user_group_memberships", (string)null);
                });

            modelBuilder.Entity("Nexorsys.Identity.Core.UserPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("expires_at");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("granted_at");

                    b.Property<Guid?>("GrantedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("granted_by");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("PermissionLevel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("permission_level");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_permissions");

                    b.HasIndex("ApplicationId")
                        .HasDatabaseName("ix_user_permissions_application_id");

                    b.HasIndex("GrantedBy")
                        .HasDatabaseName("ix_user_permissions_granted_by");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_permissions_user_id");

                    b.ToTable("user_permissions", (string)null);
                });

            modelBuilder.Entity("Nexorsys.Identity.Core.UserPin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BadgeUid")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("badge_uid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("PinHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pin_hash");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_pins");

                    b.HasIndex("BadgeUid")
                        .IsUnique()
                        .HasDatabaseName("ix_user_pins_badge_uid");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_user_pins_created_by");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_pins_user_id");

                    b.ToTable("user_pins", (string)null);
                });

            modelBuilder.Entity("Nexorsys.Identity.Core.UserRoleMembership", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_role_memberships");

                    b.ToTable("user_role_memberships", (string)null);
                });

            modelBuilder.Entity("Nexorsys.Identity.Core.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuthenticationMethod")
                        .HasColumnType("text")
                        .HasColumnName("authentication_method");

                    b.Property<string>("Department")
                        .HasColumnType("text")
                        .HasColumnName("department");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<DateTime?>("LastActivityAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("last_activity_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateTime?>("SessionEndedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("session_ended_at");

                    b.Property<DateTime>("SessionStartedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("session_started_at");

                    b.Property<string>("SessionToken")
                        .HasColumnType("text")
                        .HasColumnName("session_token");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid?>("WorkstationId")
                        .HasColumnType("uuid")
                        .HasColumnName("workstation_id");

                    b.HasKey("Id")
                        .HasName("pk_user_sessions");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_sessions_user_id");

                    b.HasIndex("WorkstationId")
                        .HasDatabaseName("ix_user_sessions_workstation_id");

                    b.ToTable("user_sessions", (string)null);
                });

            modelBuilder.Entity("Nexorsys.Identity.Core.UserWorkstation", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("WorkstationId")
                        .HasColumnType("uuid")
                        .HasColumnName("workstation_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.HasKey("UserId", "WorkstationId")
                        .HasName("pk_user_workstations");

                    b.HasIndex("WorkstationId")
                        .HasDatabaseName("ix_user_workstations_workstation_id");

                    b.ToTable("user_workstations", (string)null);
                });

            modelBuilder.Entity("Nexorsys.Identity.Core.VaultEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<byte[]>("EncryptedSecret")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("encrypted_secret");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("last_used_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<int>("SecretVersion")
                        .HasColumnType("integer")
                        .HasColumnName("secret_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_vault_entries");

                    b.ToTable("vault_entries", (string)null);
                });

            modelBuilder.Entity("Nexorsys.Identity.Core.Workflow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssignedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_by");

                    b.Property<Guid?>("AssignedTo")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_to");

                    b.Property<string>("Comments")
                        .HasColumnType("text")
                        .HasColumnName("comments");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at");

                    b.Property<string>("FormData")
                        .HasColumnType("jsonb")
                        .HasColumnName("form_data");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_workflows");

                    b.HasIndex("AssignedBy")
                        .HasDatabaseName("ix_workflows_assigned_by");

                    b.HasIndex("AssignedTo")
                        .HasDatabaseName("ix_workflows_assigned_to");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_workflows_user_id");

                    b.ToTable("workflows", (string)null);
                });

            modelBuilder.Entity("Nexorsys.Identity.Core.Workstation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("approved_at");

                    b.Property<string>("AuthenticationMode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("authentication_mode");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DecommissionedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("decommissioned_at");

                    b.Property<string>("Department")
                        .HasColumnType("text")
                        .HasColumnName("department");

                    b.Property<string>("DeviceCertificateThumbprint")
                        .HasColumnType("text")
                        .HasColumnName("device_certificate_thumbprint");

                    b.Property<DateTime?>("EnrolledAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("enrolled_at");

                    b.Property<string>("EnrollmentState")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("enrollment_state");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hostname");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("last_seen_at");

                    b.Property<DateTime?>("LastValidatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("last_validated_at");

                    b.Property<string>("Location")
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("MachineSid")
                        .HasColumnType("text")
                        .HasColumnName("machine_sid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid?>("ReplacedByWorkstationId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_workstation_id");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("revoked_at");

                    b.Property<bool>("WindowsAuthEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("windows_auth_enabled");

                    b.HasKey("Id")
                        .HasName("pk_workstations");

                    b.HasIndex("Hostname")
                        .IsUnique()
                        .HasDatabaseName("ix_workstations_hostname");

                    b.ToTable("workstations", (string)null);
                });

            modelBuilder.Entity("Nexorsys.Identity.Core.WorkstationSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CurrentUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_user_id");

                    b.Property<string>("LastBadgeSeen")
                        .HasColumnType("text")
                        .HasColumnName("last_badge_seen");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateTime?>("SessionEndedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("session_ended_at");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<DateTime>("SessionStartedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("session_started_at");

                    b.Property<Guid>("WorkstationId")
                        .HasColumnType("uuid")
                        .HasColumnName("workstation_id");

                    b.HasKey("Id")
                        .HasName("pk_workstation_sessions");

                    b.HasIndex("CurrentUserId")
                        .HasDatabaseName("ix_workstation_sessions_current_user_id");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_workstation_sessions_session_id");

                    b.HasIndex("WorkstationId")
                        .HasDatabaseName("ix_workstation_sessions_workstation_id");

                    b.ToTable("workstation_sessions", (string)null);
                });

            modelBuilder.Entity("Nexorsys.Identity.Core.AnsDelegationLog", b =>
                {
                    b.HasOne("Nexorsys.Identity.Core.User", "AdminUser")
                        .WithMany()
                        .HasForeignKey("AdminUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_ans_delegation_logs_users_admin_user_id");

                    b.HasOne("Nexorsys.Identity.Core.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ans_delegation_logs_users_user_id");

                    b.Navigation("AdminUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nexorsys.Identity.Core.ApplicationSession", b =>
                {
                    b.HasOne("Nexorsys.Identity.Core.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_application_sessions_users_user_id");

                    b.HasOne("Nexorsys.Identity.Core.Workstation", "Workstation")
                        .WithMany()
                        .HasForeignKey("WorkstationId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_application_sessions_workstations_workstation_id");

                    b.Navigation("User");

                    b.Navigation("Workstation");
                });

            modelBuilder.Entity("Nexorsys.Identity.Core.AuditLog", b =>
                {
                    b.HasOne("Nexorsys.Identity.Core.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_audit_logs_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nexorsys.Identity.Core.AuthenticationEvent", b =>
                {
                    b.HasOne("Nexorsys.Identity.Core.User", "User")
                        .WithMany("AuthenticationEvents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_authentication_events_users_user_id");

                    b.HasOne("Nexorsys.Identity.Core.Workstation", "Workstation")
                        .WithMany()
                        .HasForeignKey("WorkstationId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_authentication_events_workstations_workstation_id");

                    b.Navigation("User");

                    b.Navigation("Workstation");
                });

            modelBuilder.Entity("Nexorsys.Identity.Core.AuthenticationPolicy", b =>
                {
                    b.HasOne("Nexorsys.Identity.Core.IdentityProvider", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_authentication_policies_identity_providers_provider_id");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("Nexorsys.Identity.Core.CredentialProviderFleet", b =>
                {
                    b.HasOne("Nexorsys.Identity.Core.Workstation", "Workstation")
                        .WithOne("CredentialProviderFleet")
                        .HasForeignKey("Nexorsys.Identity.Core.CredentialProviderFleet", "WorkstationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_credential_provider_fleets_workstations_workstation_id");

                    b.Navigation("Workstation");
                });

            modelBuilder.Entity("Nexorsys.Identity.Core.FederationToken", b =>
                {
                    b.HasOne("Nexorsys.Identity.Core.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_federation_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nexorsys.Identity.Core.KioskSession", b =>
                {
                    b.HasOne("Nexorsys.Identity.Core.User", "User")
                        .WithMany("KioskSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_kiosk_sessions_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nexorsys.Identity.Core.PinResetRequest", b =>
                {
                    b.HasOne("Nexorsys.Identity.Core.User", "ApprovedByUser")
                        .WithMany()
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_pin_reset_requests_users_approved_by");

                    b.HasOne("Nexorsys.Identity.Core.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pin_reset_requests_users_user_id");

                    b.HasOne("Nexorsys.Identity.Core.Workstation", "Workstation")
                        .WithMany()
                        .HasForeignKey("WorkstationId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_pin_reset_requests_workstations_workstation_id");

                    b.Navigation("ApprovedByUser");

                    b.Navigation("User");

                    b.Navigation("Workstation");
                });

            modelBuilder.Entity("Nexorsys.Identity.Core.SessionEvent", b =>
                {
                    b.HasOne("Nexorsys.Identity.Core.UserSession", "Session")
                        .WithMany("SessionEvents")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_session_events_user_sessions_session_id");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Nexorsys.Identity.Core.UserDevice", b =>
                {
                    b.HasOne("Nexorsys.Identity.Core.User", "RegisteredByUser")
                        .WithMany()
                        .HasForeignKey("RegisteredBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_user_devices_users_registered_by");

                    b.HasOne("Nexorsys.Identity.Core.User", "User")
                        .WithMany("Devices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_devices_users_user_id");

                    b.Navigation("RegisteredByUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nexorsys.Identity.Core.UserPermission", b =>
                {
                    b.HasOne("Nexorsys.Identity.Core.Application", "Application")
                        .WithMany("UserPermissions")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_permissions_applications_application_id");

                    b.HasOne("Nexorsys.Identity.Core.User", "GrantedByUser")
                        .WithMany()
                        .HasForeignKey("GrantedBy")
                        .HasConstraintName("fk_user_permissions_users_granted_by");

                    b.HasOne("Nexorsys.Identity.Core.User", "User")
                        .WithMany("UserPermissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_permissions_users_user_id");

                    b.Navigation("Application");

                    b.Navigation("GrantedByUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nexorsys.Identity.Core.UserPin", b =>
                {
                    b.HasOne("Nexorsys.Identity.Core.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("fk_user_pins_users_created_by");

                    b.HasOne("Nexorsys.Identity.Core.User", "User")
                        .WithMany("UserPins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_pins_users_user_id");

                    b.Navigation("CreatedByUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nexorsys.Identity.Core.UserSession", b =>
                {
                    b.HasOne("Nexorsys.Identity.Core.User", "User")
                        .WithMany("UserSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_sessions_users_user_id");

                    b.HasOne("Nexorsys.Identity.Core.Workstation", "Workstation")
                        .WithMany()
                        .HasForeignKey("WorkstationId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_user_sessions_workstations_workstation_id");

                    b.Navigation("User");

                    b.Navigation("Workstation");
                });

            modelBuilder.Entity("Nexorsys.Identity.Core.UserWorkstation", b =>
                {
                    b.HasOne("Nexorsys.Identity.Core.User", "User")
                        .WithMany("UserWorkstations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_workstations_users_user_id");

                    b.HasOne("Nexorsys.Identity.Core.Workstation", "Workstation")
                        .WithMany("UserWorkstations")
                        .HasForeignKey("WorkstationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_workstations_workstations_workstation_id");

                    b.Navigation("User");

                    b.Navigation("Workstation");
                });

            modelBuilder.Entity("Nexorsys.Identity.Core.Workflow", b =>
                {
                    b.HasOne("Nexorsys.Identity.Core.User", "AssignedByUser")
                        .WithMany()
                        .HasForeignKey("AssignedBy")
                        .HasConstraintName("fk_workflows_users_assigned_by");

                    b.HasOne("Nexorsys.Identity.Core.User", "AssignedToUser")
                        .WithMany()
                        .HasForeignKey("AssignedTo")
                        .HasConstraintName("fk_workflows_users_assigned_to");

                    b.HasOne("Nexorsys.Identity.Core.User", "User")
                        .WithMany("Workflows")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflows_users_user_id");

                    b.Navigation("AssignedByUser");

                    b.Navigation("AssignedToUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nexorsys.Identity.Core.WorkstationSession", b =>
                {
                    b.HasOne("Nexorsys.Identity.Core.User", "CurrentUser")
                        .WithMany()
                        .HasForeignKey("CurrentUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_workstation_sessions_users_current_user_id");

                    b.HasOne("Nexorsys.Identity.Core.UserSession", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_workstation_sessions_user_sessions_session_id");

                    b.HasOne("Nexorsys.Identity.Core.Workstation", "Workstation")
                        .WithMany()
                        .HasForeignKey("WorkstationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workstation_sessions_workstations_workstation_id");

                    b.Navigation("CurrentUser");

                    b.Navigation("Session");

                    b.Navigation("Workstation");
                });

            modelBuilder.Entity("Nexorsys.Identity.Core.Application", b =>
                {
                    b.Navigation("UserPermissions");
                });

            modelBuilder.Entity("Nexorsys.Identity.Core.User", b =>
                {
                    b.Navigation("AuthenticationEvents");

                    b.Navigation("Devices");

                    b.Navigation("KioskSessions");

                    b.Navigation("UserPermissions");

                    b.Navigation("UserPins");

                    b.Navigation("UserSessions");

                    b.Navigation("UserWorkstations");

                    b.Navigation("Workflows");
                });

            modelBuilder.Entity("Nexorsys.Identity.Core.UserSession", b =>
                {
                    b.Navigation("SessionEvents");
                });

            modelBuilder.Entity("Nexorsys.Identity.Core.Workstation", b =>
                {
                    b.Navigation("CredentialProviderFleet");

                    b.Navigation("UserWorkstations");
                });
#pragma warning restore 612, 618
        }
    }
}
